name: DEVisible test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  devisible:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Run DEVisible NPM package
      - shell: bash
        env:
          API_KEY: ${{ secrets.devisibleKey }}
        run: |
          npx devisible --apiKey $"API_KEY" --buildPath /build --command "npm run build"
